---
title: "simulation"
author: "Sitian Zhou"
date: "2023-11-02"
output: github_document
editor_options: 
  chunk_output_type: console
---


```{r}
library(tidyverse)
library(rvest)
```



```{r}
set.seed(12345)
```



```{r}
sim_mean_sd = function(n_obs, mu = 5, sigma = 1) {
  
  x_vec = rnorm(n = n_obs, mean = mu, sd = sigma)
  
  tibble(
    mean = mean(x_vec),
    sd = sd(x_vec)
  )
  
}
```

```{r}
sim_mean_sd(n_obs = 30)
```

```{r}
output = vector("list", length = 100)

for (i in 1:100){
  output[[i]] = sim_mean_sd(n_obs = 30)
}

sim_results = 
  bind_rows(output)

sim_results |> 
  ggplot(aes(x = mean)) + geom_density()

sim_results |> 
  summarize(
    mu_hat = mean(mean),
    sd_hat = sd(mean)
  )
# mu_hat = mu; sd_hat = sigma / sqrt(n) = 1 / sqrt(30) = 0.18
```


use a map function

```{r}
sim_results_df = 
  expand_grid(
    sample_size = c(30, 60, 120, 240), 
    iter = 1:1000
  ) |> 
  mutate(
    estimate_df = map(sample_size, sim_mean_sd)
  ) |> 
  unnest(estimate_df)

sim_results_df |> 
  mutate(
    sample_size = str_c("n" = sample_size),
    sample_size = fct_inorder(sample_size)
  ) |> 
  ggplot(aes(x = sample_size, y = mean)) +
  geom_boxplot()

```

## SLR

Goal is to write a function that simulates data and then a regression; then repeat to look at the distribution of estimated coefficients

```{r}
beta_0 = 2
beta_1 = 3

sim_data = 
  tibble(
    x = rnorm(n = 30, mean = 1, sd = 1),
    y = beta_0 + beta_1 * x + rnorm(30, mean = 0, sd = 1)
  )

ls_fit = lm(y ~ x, data = sim_data)
ls_fit

sim_data |> 
  ggplot(aes(x = x, y = y)) +
  geom_point()
```

let's wrap this into a function

```{r}
sim_slr = function(n_obs, beta_0 = 2, beta_1 = 3){

  sim_data = 
    tibble(
      x = rnorm(n = 30, mean = 1, sd = 1),
      y = beta_0 + beta_1 * x + rnorm(30, mean = 0, sd = 1)
    )
  ls_fit = lm(y ~ x, data = sim_data)
  
  tibble(
    beta0_hat = coef(ls_fit)[1],
    beta1_hat = coef(ls_fit)[2]
  )
}

sim_slr(n_obs = 30)
```

run this a whole bunch of times

```{r}
sim_results_df = 
  expand_grid(
    sample_size = 30,
    iter = 1:1000
  ) |> 
  mutate(
    estimate_df = map(sample_size, sim_slr)
  ) |> 
  unnest(estimate_df)

```


Let's look at results

```{r}
sim_results_df |> 
  summarize(
    mean_b0_hat = mean(beta0_hat),
    mean_b1_hat = mean(beta1_hat)
  )

sim_results_df |> 
  ggplot(aes(x = beta0_hat)) +
  geom_histogram()

sim_results_df |> 
  ggplot(aes(x = beta0_hat, y = beta1_hat)) +
  geom_point()

```









