---
title: "writing_functions"
author: "Sitian Zhou"
date: "2023-10-26"
output: github_document
---


```{r}
library(tidyverse)
library(rvest)
```


## Z score function
```{r}
set.seed(12345)
```

## Z score function

z scores

```{r}
x_vec = rnorm(20, mean = 5, sd = 0.3)

```


compute z scores for `x_vec`

```{r}
(x_vec - mean(x_vec)) / sd(x_vec)
```


write a function for calculating z scores

```{r}
z_score = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument should be numebrs")
  } else if (length(x) < 2) {
    stop("You need at least 2 numbers to get z scores")
  }
  
  z = (x - mean(x)) / sd(x)
  z
}
```

```{r}
z_score(x = x_vec)
```

```{r, error=TRUE}
z_score(3)
z_score(c("a", "b", "c"))
z_score(c(TRUE, TRUE, FALSE, FALSE))
z_score(iris)
```


## Multiple outputs

write a function that returns the mean and sd from a sample of numbers.

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument should be numebrs")
  } else if (length(x) < 2) {
    stop("You need at least 2 numbers to get z scores")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
}
```

```{r}
mean_and_sd(x_vec)
```

## Start getting means and sds

```{r}
x_vec = rnorm(n = 30, mean = 5, sd = 0.5)



tibble(
  mean = mean(x_vec),
  sd = sd(x_vec)
)

```
Lets write a function that uses `n`, a true mean, and true sd as inputs

```{r}
sim_mean_sd = function(n_obs, mu = 5, sigma = 1) {
  
  x_vec = rnorm(n = n_obs, mean = mu, sd = sigma)
  
  tibble(
    mean = mean(x_vec),
    sd = sd(x_vec)
  )
  
}
```


```{r}
sim_mean_sd(n_obs = 30, mu = 50)

sim_mean_sd(12, 24, 4) # position matching

sim_mean_sd(mu = 24, n_obs = 12, sigma = 4) # you can change the order of inputs
```




















